### ISSUE TITLE
Is it possible to share tensor calculus slides for lecture 21-26?

### ISSUE THREAD

**Issue by pu-wei** [eigenchris/MathNotes#1]
Thank you very much, Chris. The tensor calculus series are very enlightening. 
Is it possible to share the lecture slides (from Lie bracket till the end)?

**Comment by Bellenium** [comment]
I'd like to second this

**Comment by Bharath-Shan** [comment]
Hey Chirs.  Thanks for the amazing lecture series.  It would be so kind of you if you can post remaining slides. Thank you.

**Comment by SKacademics** [comment]
Yo, thanks dude. I don't think my current understanding of Tensors & Tensor Calculus could be so clear w/o your help.

One question though - have the slides been corrected? Or should I refer back to the corrections you put in the YouTube description? 

Many Thanks

**Comment by eigenchris** [comment]
Added the slides about 8 months ago. I've corrected any mistakes I've found, but there is always the possibility that there are more. You can feel free to leave a comment if you notice any mistakes.
